export const mockNumbers = [
    {
        image:'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/MAXVER01.png.transform/2col/image.png',
        number:1
    },
    {
        image:'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/CHALEC01.png.transform/2col/image.png',
        number:16
    },
    {
        image:'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/SERPER01.png.transform/2col/image.png',
        number:11
    },
    {
        image:'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/CARSAI01.png.transform/2col/image.png',
        number:55
    },
    {
        image:'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/GEORUS01.png.transform/2col/image.png',
        number:63
    },
    {
        image:'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/LEWHAM01.png.transform/2col/image.png',
        number:44
    },
    {
        image:'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/LANNOR01.png.transform/2col/image.png',
        number:4
    },
    {
        image:'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/ESTOCO01.png.transform/2col/image.png',
        number:31
    },
    {
        image:'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/VALBOT01.png.transform/2col/image.png',
        number:77
    },
    {
        image:'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/FERALO01.png.transform/2col/image.png',
        number:14
    },
    {
        image:'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/KEVMAG01.png.transform/2col/image.png',
        number:20
    },
    {
        image:'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/DANRIC01.png.transform/2col/image.png',
        number:3
    },
    {
        image:'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/PIEGAS01.png.transform/2col/image.png',
        number:10
    },
    {
        image:'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/SEBVET01.png.transform/2col/image.png',
        number:5
    },
    {
        image:'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/MICSCH02.png.transform/2col/image.png',
        number:47
    },
    {
        image:'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/YUKTSU01.png.transform/2col/image.png',
        number:22
    },
    {
        image:'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/GUAZHO01.png.transform/2col/image.png',
        number:24
    },
    {
        image:'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/ALEALB01.png.transform/2col/image.png',
        number:23
    },
    {
        image:'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/LANSTR01.png.transform/2col/image.png',
        number:18
    },
    {
        image: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/NICLAF01.png.transform/2col/image.png',
        number:6
    },
    {
        image:'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/NICHUL01.png.transform/2col/image.png',
        number:27
    }
];